name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 0
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
        bundler: 1
    - run: sudo npm install -g svgo
    - run: curl -L "https://www.jonof.id.au/files/kenutils/pngout-20200115-linux.tar.gz" | sudo tar -xz -C /usr/local/bin --strip-components 2 --wildcards '*/amd64/pngout'
    - run: RUBYOPT=-rset bundle exec appraisal install --jobs=3 --retry=3
    - run: bundle exec image_optim --info
    - run: bundle exec appraisal rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - run: bundle exec rubocop
