name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 0
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '2.3'
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: sudo npm install -g svgo
    - run: RUBYOPT=-rset bundle exec appraisal install --jobs=3 --retry=3
    - run: bundle exec image_optim --info
    - run: bundle exec appraisal rspec
